title: My GitHub Blog
description: A simple blog powered by GitHub Pages and Jekyll
baseurl: "/rylkoroman/" # оставляем пустым для корня
url: "https://rylkoroman.github.io/rylkoroman/" # без слеша в конце
theme: minima
